spring:
  application:
    name: api1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:13306/webdb3
#    username: webdb3user
#    password: webdb3user
    url: jdbc:mariadb://10.10.10.158:3306/cleanaido
    username: cleanaidouser
    password: cleanaidouser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      location: upload
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

org:
  zerock:
    accessTime: 1
    refreshTime: 10080
    alwaysNew: true
    upload:
      path: upload

jwt:
  secretKey: jakCELGsH3DsQsw2RTSLuQokILHO/A3wRn6GWuao3EQ=

logging:
  level:
    org.springframework.security.web: TRACE